language: scala
scala:
  - 2.11.8

jdk:
  - oraclejdk8

install:
  - pip install --user codecov

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test &&
    sbt ++$TRAVIS_SCALA_VERSION coverageReport && codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)